docker)
      appTitle="Docker Desktop"
      appProcesses+=("Docker")
      appProcesses+=("Docker Desktop")
      appProcesses+=("com.docker.hyperkit")
      appFiles+=("/Applications/Utilities/Docker.app")
      appFiles+=("/Users/$loggedInUser/Library/Application Scripts/com.docker.helper")
      appFiles+=("/Users/$loggedInUser/Library/Caches/com.docker.docker")
      appFiles+=("/Users/$loggedInUser/Library/Containers/com.docker.docker")
      appFiles+=("/Users/$loggedInUser/Library/Containers/com.docker.helper")
      appFiles+=("/Library/PrivilegedHelperTools/com.docker.vmnetd")
      appFiles+=("/Users/$loggedInUser/.docker")
      appFiles+=("/Users/$loggedInUser/Library/Application Support/Docker Desktop")
      appFiles+=("/Users/$loggedInUser/Library/Preferences/com.docker.docker.plist")
      appFiles+=("/Users/$loggedInUser/Library/Saved Application State/com.electron.docker-frontend.savedState")
      appFiles+=("/Users/$loggedInUser/Library/Group Containers/group.com.docker")
      appFiles+=("/Users/$loggedInUser/Library/Logs/Docker Desktop")
      appFiles+=("/Users/$loggedInUser/Library/Preferences/com.electron.docker-frontend.plist")
      appFiles+=("/Users/$loggedInUser/Library/Cookies/com.docker.docker.binarycookies")
      appFiles+=("/usr/local/lib/docker")
      appFiles+=("/usr/local/bin/docker-machine")
      appFiles+=("/usr/local/bin/docker-compose")
      appFiles+=("/usr/local/bin/docker-credential-osxkeychain")
      appFiles+=("/usr/local/lib/docker")
      appLaunchAgents+=("/Library/LaunchDaemons/com.docker.vmnetd.plist")
      preflightCommand+=("/Applications/Docker.app/Contents/MacOS/Docker --uninstall")
      ;;
