1password)
      appTitle="1Password"
      appProcesses+=("1Password 7")
      appProcesses+=("1Password Extension Helper")
      appProcesses+=("1password")
      appFiles+=("/Applications/1Password.app")
      appFiles+=("/Users/$loggedInUser/Library/Application Support/1Password")
      appFiles+=("/Users/$loggedInUser/Library/Preferences/com.agilebits.onepassword.plist")
      appFiles+=("/Users/$loggedInUser/Library/Containers/1Password")
      appFiles+=("/Users/$loggedInUser/Library/Containers/1Password 7")
      appFiles+=("/Users/$loggedInUser/Library/Containers/1Password Launcher")
      appFiles+=("/Users/$loggedInUser/Library/Containers/2BUA8C4S2C.com.agilebits.onepassword7-helper")
      appFiles+=("/Users/$loggedInUser/Library/Group Containers/2BUA8C4S2C.com.agilebits")
      appFiles+=("/Users/$loggedInUser/Library/HTTPStorages/com.agilebits.onepassword7-updater")
      appFiles+=("/Users/$loggedInUser/Library/Logs/1Password")
      appFiles+=("/Users/$loggedInUser/Library/Application Support/")
      appFiles+=("/Users/$loggedInUser/Library/Application Scripts/2BUA8C4S2C.com.agilebits")
      appFiles+=("/Users/$loggedInUser/Library/Application Scripts/2BUA8C4S2C.com.agilebits.onepassword7-helper")
      appFiles+=("/Users/$loggedInUser/Library/Application Scripts/com.agilebits.onepassword7")
      appFiles+=("/Users/$loggedInUser/Library/Application Scripts/com.agilebits.onepassword7-launcher")
      appFiles+=("/Users/$loggedInUser/Library/Application Scripts/com.agilebits.onepassword7.1PasswordSafariAppExtension")
      appFiles+=("/Users/$loggedInUser/Library/Application Scripts/com.agilebits.onepasswordslsnativemessaginghost")
      appFiles+=("/Users/$loggedInUser/Library/Caches/com.agilebits.onepassword7-updater")
      appFiles+=("/Users/$loggedInUser/Library/Caches/com.apple.Safari/Extensions/")
      appFiles+=("/Users/$loggedInUser/Library/WebKit/com.agilebits.onepassword4/")
      ;;
