asperaconnect)
      appTitle="Aspera Connect"
      appProcesses+=("IBM Aspera Connect" "IBM Aspera Crypt" "IBM Aspera Launcher")
      appFiles+=("/Applications/IBM Aspera Connect.app")
      appFiles+=("/Applications/IBM Aspera Crypt.app")
      appFiles+=("/Applications/IBM Aspera Launcher.app")
      appFiles+=("/Library/Application Support/Aspera/Aspera Connect")
      appFiles+=("<<Users>>/.aspera/connect")
      appFiles+=("<<Users>>/Library/Application Scripts/com.ibm.software.aspera.connect.safariextension")
      appFiles+=("<<Users>>/Library/Application Scripts/com.ibm.software.aspera.connect.sendtoextension")
      appFiles+=("<<Users>>/Library/Application Scripts/PETKK2G752.com.ibm.software.aspera.connect")
      appFiles+=("<<Users>>/Library/Preferences/com.asperasoft.IBM Aspera Crypt.plist")
      appFiles+=("<<Users>>/Library/Preferences/com.ibm.software.aspera.connect.plist")
      appFiles+=("<<Users>>/Library/Logs/Aspera_Connect")
      appReceipts+=("com.ibm.software.aspera.connect")
      appReceipts+=("com.ibm.software.aspera.crypt")
      appReceipts+=("com.ibm.software.aspera.desktop")
      appReceipts+=("com.ibm.software.aspera.launcher")
      preflightCommand+=('"/Applications/IBM Aspera Connect.app/Contents/MacOS/asperaconnect-nmh" --unregister')
      ;;
