bbedit)
      appTitle="BBEdit"
      appProcesses+=("BBEdit")
      appFiles+=("/Applications/BBEdit.app")
      appFiles+=("<<Users>>/Library/Application Support/BBEdit")
      appFiles+=("<<Users>>/Library/Preferences/com.barebones.bbedit.plist")
      appFiles+=("<<Users>>/Library/Containers/com.barebones.bbedit")
      appFiles+=("<<Users>>/Library/Application Scripts/com.barebones.bbedit")
      appFiles+=("<<Users>>/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/com.barebones.bbedit.sfl2")
      appFiles+=("/usr/local/bin/bbdiff")
      appFiles+=("/usr/local/bin/bbedit")
      appFiles+=("/usr/local/bin/bbfind")
      appFiles+=("/usr/local/bin/bbresults")      
      postflightCommand+=("rm -r /Users/$loggedInUser/Library/Caches/com.apple.helpd/Generated/com.barebones.bbedit.help*")
      ;;
