boxdrive)
      appTitle="Box Drive"
      appProcesses+=("Box")
      appFiles+=("/Applications/Box.app")
      appFiles+=("/Library/Application Support/Box")
      appLaunchAgents+=("/Library/LaunchAgents/com.box.desktop.helper.plist")
      appLaunchDaemons+=("/Library/LaunchDaemons/com.box.desktop.autoupdater.plist")
      appFiles+=("/Library/Logs/Box")
      appFiles+=("/Library/Preferences/com.box.desktop.plist")
      appFiles+=("<<Users>>/Library/Application Scripts/com.box.desktop.boxfileprovider")
      appFiles+=("<<Users>>/Library/Application Scripts/com.box.desktop.findersyncext")
      appFiles+=("<<Users>>/Library/Application Support/Box")
      appFiles+=("<<Users>>/Library/Containers/com.box.desktop.boxfileprovider")
      appFiles+=("<<Users>>/Library/Containers/com.box.desktop.findersyncext")
      appFiles+=("<<Users>>/Library/Group Containers/M683GB7CPW.b")
      appLaunchAgents+=("<<Users>>/Library/LaunchAgents/com.box.desktop.launch.plist")
      appFiles+=("<<Users>>/Library/Logs/Box")
      appFiles+=("<<Users>>/Library/Logs/Box/Box/com.box.desktop.ui-stderr.txt")
      appFiles+=("<<Users>>/Library/Preferences/com.box.desktop.plist")
      appFiles+=("<<Users>>/Library/Preferences/com.box.desktop.ui.plist")
      appReceipts+=("com.box.desktop.installer.autoupdater")
      appReceipts+=("com.box.desktop.installer.desktop")
      appReceipts+=("com.box.desktop.installer.local.appsupport")
      ;;
