boxtools)
      appTitle="Box Tools"
      appProcesses+=("Box Edit" "Box Local Com Server" "Box Tools Custom Apps" "Box Device Trust")
      appFiles+=("/Library/Application Support/Box/Box Edit/Box Device Trust.app")
      appFiles+=("/Library/Application Support/Box/Box Edit/Box Edit.app")
      appFiles+=("/Library/Application Support/Box/Box Edit/Box Local Com Server.app")
      appFiles+=("/Library/Application Support/Box/Box Edit/Box Tools Custom Apps.app")
      appFiles+=("/Library/Application Support/Box")
      appFiles+=("/Library/Preferences/com.box.deviceId.plist")
      appFiles+=("<<Users>>/Library/Application Scripts/com.Box.Box-Edit.BoxEditFinderExtension")
      appFiles+=("<<Users>>/Library/Caches/com.Box.Box-Edit")
      appFiles+=("<<Users>>/Library/Containers/com.Box.Box-Edit.BoxEditFinderExtension")
      appFiles+=("<<Users>>/Library/Group Containers/M683GB7CPW.com.box.tools")
      appFiles+=("<<Users>>/Library/HTTPStorages/com.Box.Box-Edit")
      appFiles+=("<<Users>>/Library/Logs/Box")
      appFiles+=("<<Users>>/Library/Logs/Box/Box Local Com Server")
      appFiles+=("<<Users>>/Library/Preferences/com.Box.Box-Edit.plist")
      appFiles+=("<<Users>>/Library/Preferences/com.box.Box-Local-Com-Server.plist")
      appFiles+=("<<Users>>/Library/Preferences/com.box.Box-Device-Trust.plist")
      appLaunchAgents+=("<<Users>>/Library/LaunchAgents/com.Box.Box-Edit.launch.plist")
      appLaunchAgents+=("<<Users>>/Library/LaunchAgents/com.box.Box-Local-Com-Server.launch.plist")
      appLaunchAgents+=("<<Users>>/Library/LaunchAgents/com.box.Box-Device-Trust.launch.plist")
      appReceipts+=("com.box.boxtools.installer.boxcustomapps")
      appReceipts+=("com.box.boxtools.installer.boxdevicetrust")
      appReceipts+=("com.box.boxtools.installer.boxedit")
      appReceipts+=("com.box.boxtools.installer.boxlocalcomserver")
      ;;
