dropbox)
      appTitle="Dropbox"
      appProcesses+=("Dropbox")
      appFiles+=("/Applications/Dropbox.app")
      appFiles+=("/Users/$loggedInUser/Library/Application Scripts/com.getdropbox.dropbox.TransferExtension")
      appFiles+=("/Users/$loggedInUser/Library/Application Scripts/com.getdropbox.dropbox.fileprovider")
      appFiles+=("/Users/$loggedInUser/Library Application Scripts/com.getdropbox.dropbox.garcon")
      appFiles+=("/Users/$loggedInUser/Library Application Support/Dropbox")
      appFiles+=("/Users/$loggedInUser/Library/Containers/com.getdropbox.dropbox.TransferExtension")
      appFiles+=("/Users/$loggedInUser/Library/Containers/com.getdropbox.dropbox.fileprovider")
      appFiles+=("/Users/$loggedInUser/Library/Containers/com.getdropbox.dropbox.garcon")
      appFiles+=("/Users/$loggedInUser/Library/Dropbox")
      appFiles+=("/Users/$loggedInUser/Library/Group Containers/G7HH3F8CAK.com.getdropbox.dropbox.sync")
      appFiles+=("/Users/$loggedInUser/Library/Group Containers/com.dropbox.client.crashpad")
      appFiles+=("/Users/$loggedInUser/Library/LaunchAgents/com.dropbox.DropboxMacUpdate.agent.plist")
      appFiles+=("/Users/$loggedInUser/Library/Preferences/com.dropbox.DropboxMacUpdate.plist")
      appFiles+=("/Users/$loggedInUser/Library/Preferences/com.getdropbox.dropbox.plist")
      ;;
