dropbox)
      appTitle="Dropbox"
      appProcesses+=("Dropbox")
      appFiles+=("/Applications/Dropbox.app")
      appFiles+=("<<Users>>/.dropbox")
      appFiles+=("<<Users>>/Library/Application Scripts/com.getdropbox.dropbox.TransferExtension")
      appFiles+=("<<Users>>/Library/Application Scripts/com.getdropbox.dropbox.fileprovider")
      appFiles+=("<<Users>>/Library/Application Scripts/com.getdropbox.dropbox.garcon")
      appFiles+=("<<Users>>/Library/Application Scripts/com.dropbox.alternatenotificationservice")
      appFiles+=("<<Users>>/Library/Application Scripts/com.dropbox.client.crashpad")
      appFiles+=("<<Users>>/Library/Application Scripts/G7HH3F8CAK.com.getdropbox.dropbox.sync")
      appFiles+=("<<Users>>/Library/Application Support/Dropbox")
      appFiles+=("<<Users>>/Library/QuickLook/DropboxQL.qlgenerator")
      #appFiles+=("<<Users>>/Library/Application Support/FileProvider/com.getdropbox.dropbox.fileprovider")
      appFiles+=("<<Users>>/Library/Containers/com.getdropbox.dropbox.TransferExtension")
      appFiles+=("<<Users>>/Library/Containers/com.getdropbox.dropbox.fileprovider")
      appFiles+=("<<Users>>/Library/Containers/com.getdropbox.dropbox.garcon")
      appFiles+=("<<Users>>/Library/Containers/com.dropbox.alternatenotificationservice")
      appFiles+=("<<Users>>/Library/Dropbox")
      appFiles+=("<<Users>>/Library/HTTPStorages/com.dropbox.DropboxMacUpdate")
      appFiles+=("<<Users>>/Library/Group Containers/G7HH3F8CAK.com.getdropbox.dropbox.sync")
      appFiles+=("<<Users>>/Library/Group Containers/com.dropbox.client.crashpad")
      appFiles+=("<<Users>>/Library/Preferences/com.dropbox.DropboxMacUpdate.plist")
      appFiles+=("<<Users>>/Library/Preferences/com.getdropbox.dropbox.plist")
      appLaunchAgents+=("<<Users>>/Library/LaunchAgents/com.dropbox.DropboxMacUpdate.agent.plist")
      ;;
