googlechrome)
      appTitle="Google Chrome"
      appProcesses+=("Google Chrome")
      appFiles+=("/Applications/Google Chrome.app")
      appFiles+=("<<Users>>/Library/Application Support/Google/Chrome")
      appFiles+=("<<Users>>/Library/Preferences/com.google.Chrome.plist")
      appFiles+=("<<Users>>/Library/Preferences/com.google.Keystone.Agent.plist")
      appFiles+=("<<Users>>/Library/Caches/com.google.Keystone")
      appFiles+=("<<Users>>/Library/Caches/com.google.SoftwareUpdate")
      appFiles+=("<<Users>>/Library/Caches/Google")
      appFiles+=("<<Users>>/Library/Google")
      appFiles+=("<<Users>>/Library/HTTPStorages/com.google.Keystone")
      appFiles+=("<<Users>>/Library/Saved Application State/com.google.Chrome.savedState")
      appFiles+=("/Library/Google/Chrome")
      appLaunchAgents+=("/Library/LaunchAgents/com.google.keystone.xpcservice.plist")
      appLaunchAgents+=("/Library/LaunchAgents/com.google.keystone.agent.plist")
      appLaunchAgents+=("<<Users>>/Library/LaunchAgents/com.google.keystone.xpcservice.plist")
      appLaunchAgents+=("<<Users>>/Library/LaunchAgents/com.google.keystone.agent.plist")
      appLaunchAgents+=("<<Users>>/Library/LaunchAgents/com.google.keystone.system.agent.plist")
      appLaunchAgents+=("<<Users>>/Library/LaunchAgents/com.google.keystone.xpcservice.plist")
      ;;
