logioptionsplus)
      appTitle="Logi Options+"
      appFiles+=("/Applications/logioptionsplus.app")
      appFiles+=("/Users/Shared/logi")
      appFiles+=("/Users/Shared/LogiOptionsPlus")
      appFiles+=("<<Users>>/Library/Application Support/Logitech/LogiOptionsPlus")
      appFiles+=("<<Users>>/Library/Application Support/com.logitech.logiaipromptbuilder")
      appFiles+=("<<Users>>/Library/Application Support/LogiOptionsPlus")
      appFiles+=("<<Users>>/Library/Application Support/Logi")
      appFiles+=("/Library/Application Support/Logitech.localized/LogiOptionsPlus")
      appFiles+=("/Library/LaunchAgents/com.logi.optionsplus.plist")
      appLaunchDaemons+=("/Library/LaunchDaemons/com.logi.optionsplus.updater.plist")
      appLaunchAgents+=("/Library/LaunchAgents/com.logi.optionsplus.plist")
      appReceipts+=("com.logi.optionsplus.installer")
      ;;
