microsoftword)
# Needs more testing
      appTitle="Microsoft Word"
      appFiles+=("/Applications/Microsoft Word.app")
      appFiles+=("/Library/Preferences/com.microsoft.Word.plist")
      appFiles+=("/Library/Managed Preferences/com.microsoft.Word.plist")
      appFiles+=("$loggedInUser/Library/Preferences/com.microsoft.Word.plist")
      appFiles+=("$loggedInUser/Library/Containers/com.microsoft.Word")
      appFiles+=("$loggedInUser/Library/Application Scripts/com.microsoft.Word")
      appFiles+=("/Applications/.Microsoft Word.app.installBackup")
      appFiles+=("/Library/Application Support/Microsoft/Office365/User Content.localized/Startup.localized/Word")
      appFiles+=("/Library/Application Support/Microsoft/Office365/User Content.localized/Templates.localized/*.dot")
      appFiles+=("/Library/Application Support/Microsoft/Office365/User Content.localized/Templates.localized/*.dotx")
      appFiles+=("/Library/Application Support/Microsoft/Office365/User Content.localized/Templates.localized/*.dotm")
      appFiles+=("$loggedInUser/Library/Group Containers/UBF8T346G9.Office/User Content.localized/Startup.localized/Word")
      appFiles+=("$loggedInUser/Library/Group Containers/UBF8T346G9.Office/User Content.localized/Templates.localized/*.dot")
      appFiles+=("$loggedInUser/Library/Group Containers/UBF8T346G9.Office/User Content.localized/Templates.localized/*.dotx")
      appFiles+=("$loggedInUser/Library/Group Containers/UBF8T346G9.Office/User Content.localized/Templates.localized/*.dotm")
      appFiles+=("$loggedInUser/Library/Group Containers/UBF8T346G9.Office/mip_policy")
      appFiles+=("$loggedInUser/Library/Group Containers/UBF8T346G9.Office/FontCache")
      appFiles+=("$loggedInUser/Library/Group Containers/UBF8T346G9.Office/ComRPC32")
      appFiles+=("$loggedInUser/Library/Group Containers/UBF8T346G9.Office/TemporaryItems")
      appFiles+=("$loggedInUser/Library/Group Containers/UBF8T346G9.Office/Microsoft Office ACL*")
      appFiles+=("$loggedInUser/Library/Group Containers/UBF8T346G9.Office/MicrosoftRegistrationDB.reg")
      ;;