microsoftdefender)
      appTitle="Microsoft Defender"
      appProcesses+=("wdav" "Microsoft Defender")
      appFiles+=("/Applications/Microsoft Defender.app")
      appFiles+=("<<Users>>/Library/Preferences/com.microsoft.wdav.mainux.plist")
      appFiles+=("<<Users>>/Library/Preferences/com.microsoft.wdav.plist")
      appFiles+=("<<Users>>/Library/Preferences/com.microsoft.wdav.tray.plist")
      appFiles+=("/Library/Preferences/com.microsoft.wdav.tray.plist")
      appFiles+=("/Library/Application Support/Microsoft/Defender")
      appFiles+=("/Library/Application Support/Microsoft/DLP")
      appFiles+=("<<Users>>/Library/Application Support/com.microsoft.wdav.tray")
      appFiles+=("<<Users>>/Library/Application Support/com.microsoft.wdav.mainux")
      appFiles+=("<<Users>>/Library/Group Containers/UBF8T346G9.com.microsoft.wdav")
      appLaunchAgents+=("/Library/LaunchAgents/com.microsoft.wdav.tray.plist")
      appLaunchDaemons+=("/Library/LaunchDaemons/com.microsoft.fresno.plist")
      appLaunchDaemons+=("/Library/LaunchDaemons/com.microsoft.fresno.uninstall.plist")
      appLaunchDaemons+=("/Library/LaunchDaemons/com.microsoft.dlp.install_monitor.plist")
      ;;
