microsoftautoupdate)
      appTitle="Microsoft AutoUpdate"
      appProcesses+=("Microsoft AutoUpdate")
      appFiles+=("/Library/Application Support/Microsoft/MAU2.0/Microsoft AutoUpdate.app")
      appFiles+=("/Library/Application Support/Microsoft/MAU2.0")
      appFiles+=("/Library/Caches/com.microsoft.autoupdate.fba")
      appFiles+=("/Library/Preferences/com.microsoft.autoupdate2.plist")
      appFiles+=("<<Users>>/Library/Application Scripts/com.microsoft.errorreporting")
      appFiles+=("<<Users>>/Library/Caches/com.microsoft.autoupdate.fba")
      appFiles+=("<<Users>>/Library/Caches/com.microsoft.autoupdate2")
      appFiles+=("<<Users>>/Library/Containers/com.microsoft.errorreporting")
      appFiles+=("<<Users>>/Library/Group Containers/UBF8T346G9.Office")
      appFiles+=("<<Users>>/Library/Group Containers/UBF8T346G9.ms")
      appFiles+=("<<Users>>/Library/HTTPStorages/com.microsoft.autoupdate2")
      appFiles+=("<<Users>>/Library/Preferences/com.microsoft.autoupdate.fba.plist")
      appFiles+=("<<Users>>/Library/Preferences/com.microsoft.autoupdate2.plist")
      appLaunchAgents+=("/Library/LaunchAgents/com.microsoft.update.agent.plist")
      appLaunchDaemons+=("/Library/LaunchDaemons/com.microsoft.autoupdate.helper.plist")
      ;;
