microsoftedge)
      appTitle="Microsoft Edge"
      appFiles+=("/Applications/Microsoft Edge.app")
      appFiles+=("/Users/$loggedInUser/Library/Application Support/Microsoft Edge")
      appFiles+=("/Users/$loggedInUser/Library/Caches/Microsoft Edge")
      appFiles+=("/Users/$loggedInUser/Library/Saved Application State/com.microsoft.edgemac.savedState")
      appFiles+=("/Users/$loggedInUser/Library/WebKit/com.microsoft.edgemac")
      appFiles+=("/Users/$loggedInUser/Library/Microsoft/EdgeUpdater")
      appFiles+=("/Users/$loggedInUser/Library/Preferences/com.microsoft.edgemac.plist")
      appFiles+=("/Users/$loggedInUser/Library/HTTPStorages/com.microsoft.edgemac")
      appFiles+=("/Users/$loggedInUser/Library/Application Scripts/com.microsoft.edgemac.wdgExtension")
      appFiles+=("/Users/$loggedInUser/Library/Containers/com.microsoft.edgemac.wdgExtension")
      appFiles+=("/Library/Microsoft/Edge")
      appFiles+=("/Users/$loggedInUser/Library/Application Support/Microsoft/EdgeUpdater")
      appLaunchAgents+=("/Users/$loggedInUser/Library/LaunchAgents/com.microsoft.EdgeUpdater.update.plist")
      postflightCommand+=("rm /Users/$loggedInUser/Library/LaunchAgents/com.microsoft.EdgeUpdater.*")
      ;;
