microsoftedge)
      appTitle="Microsoft Edge"
      appFiles+=("/Applications/Microsoft Edge.app")
      appFiles+=("<<Users>>/Library/Application Support/Microsoft Edge")
      appFiles+=("<<Users>>/Library/Caches/Microsoft Edge")
      appFiles+=("<<Users>>/Library/Saved Application State/com.microsoft.edgemac.savedState")
      appFiles+=("<<Users>>/Library/WebKit/com.microsoft.edgemac")
      appFiles+=("<<Users>>/Library/Microsoft/EdgeUpdater")
      appFiles+=("<<Users>>/Library/Preferences/com.microsoft.edgemac.plist")
      appFiles+=("<<Users>>/Library/HTTPStorages/com.microsoft.edgemac")
      appFiles+=("<<Users>>/Library/Application Scripts/com.microsoft.edgemac.wdgExtension")
      appFiles+=("<<Users>>/Library/Containers/com.microsoft.edgemac.wdgExtension")
      appFiles+=("/Library/Microsoft/Edge")
      appFiles+=("<<Users>>/Library/Application Support/Microsoft/EdgeUpdater")
      appLaunchAgents+=("<<Users>>/Library/LaunchAgents/com.microsoft.EdgeUpdater.update.plist")
      postflightCommand+=("rm /Users/$loggedInUser/Library/LaunchAgents/com.microsoft.EdgeUpdater.*")
      ;;
