notion)
      appTitle="Notion"      
      appProcesses+=("Notion")
      appFiles+=("/Applications/Notion.app")
      appFiles+=("<<Users>>/Library/Application Support/Notion")
      appFiles+=("<<Users>>/Library/Application Support/Notion Calendar")
      appFiles+=("<<Users>>/Library/Caches/notion.id")
      appFiles+=("<<Users>>/Library/Caches/notion.id.ShipIt")
      appFiles+=("<<Users>>/Library/HTTPStorages/notion.id")
      appFiles+=("<<Users>>/Library/Logs/Notion")
      appFiles+=("<<Users>>/Library/Preferences/notion.id.plist")
      appFiles+=("<<Users>>/Library/Saved Application State/notion.id.savedState")
      appReceipts+=("notion.id.arm64")
      appReceipts+=("notion.id")
      appReceipts+=("notion.id.x64")
      ;;
