proxyman)
      appTitle="Proxyman"
      appProcesses+=("Proxyman")
      appFiles+=("/Applications/Proxyman.app")
      appFiles+=("/Users/$loggedInUser/Library/Preferences/com.proxyman.iconappmanager.userdefaults.plist")
      appFiles+=("/Users/$loggedInUser/Library/Preferences/com.proxyman.NSProxy.plist")
      appFiles+=("/Users/$loggedInUser/Library/Application Support/com.proxyman.NSProxy")
      appFiles+=("/Users/$loggedInUser/Library/Caches/Proxyman")
      appFiles+=("/Users/$loggedInUser/Library/Caches/com.proxyman.NSProxy")
      appFiles+=("/Users/$loggedInUser/Library/HTTPStorages/com.proxyman.NSProxy")
      appFiles+=("/Users/$loggedInUser/Library/Saved Application State/com.proxyman.NSProxy.savedState")
      appFiles+=("/Users/$loggedInUser/Library/WebKit/com.proxyman.NSProxy")
      appFiles+=("/Library/LaunchDaemons/com.proxyman.NSProxy.HelperTool.plist")
      appFiles+=("/Library/PrivilegedHelperTools/com.proxyman.NSProxy.HelperTool")
      ;;
