redshift)
      appTitle="Redshift"
      appProcesses+=( "Maya" "Cinema 4D" )
      appFiles+=("/Applications/redshift")
      appFiles+=("/Applications/Cinema 4D R21/plugins/Redshift")
      appFiles+=("/Applications/Cinema 4D R22/plugins/Redshift")
      appFiles+=("/Applications/Cinema 4D R23/plugins/Redshift")
      appFiles+=("/Applications/Cinema 4D R24/plugins/Redshift")
      appFiles+=("/Applications/Cinema 4D R25/plugins/Redshift")
      appFiles+=("/Applications/Cinema 4D R26/plugins/Redshift")
      appFiles+=("/Applications/Cinema 4D 2023/plugins/Redshift")
      appFiles+=("/Applications/Cinema 4D 2024/plugins/Redshift")
      appFiles+=("/Applications/Autodesk/maya2018/Maya.app/Contents/modules/redshift4maya.mod")
      appFiles+=("/Applications/Autodesk/maya2019/Maya.app/Contents/modules/redshift4maya.mod")
      appFiles+=("/Applications/Autodesk/maya2020/Maya.app/Contents/modules/redshift4maya.mod")
      appFiles+=("/Applications/Autodesk/maya2022/Maya.app/Contents/modules/redshift4maya.mod")
      appFiles+=("/Applications/Autodesk/maya2023/Maya.app/Contents/modules/redshift4maya.mod")
      appFiles+=("/Applications/Autodesk/maya2024/Maya.app/Contents/modules/redshift4maya.mod")
      appFiles+=("<<Users>>/redshift")
      ;;
