rightfont)
      appTitle="RightFont"
      appProcesses+=("RightFont")
      appFiles+=("/Applications/RightFont.app/")
      appFiles+=("<<Users>>/Library/Application Scripts/com.rightfontapp.RightFontHelper")
      appFiles+=("<<Users>>/Library/Application Support/CrashReporter/RightFont_AB72377B-AF64-597F-817B-BCD24A8D6BC1.plist")
      appFiles+=("<<Users>>/Library/Application Support/com.rightfontapp.RightFont5")
      appFiles+=("<<Users>>/Library/Caches/com.rightfontapp.RightFont5")
      appFiles+=("<<Users>>/Library/Containers/com.rightfontapp.RightFontHelper")
      appFiles+=("<<Users>>/Library/HTTPStorages/com.rightfontapp.RightFont5")
      appFiles+=("<<Users>>/Library/Logs/RightFont")
      appFiles+=("<<Users>>/Library/Preferences/com.rightfontapp.RightFont5.plist")
      appFiles+=("<<Users>>/Library/Saved Application State/com.rightfontapp.RightFont5.savedState")
      appFiles+=("<<Users>>/Library/WebKit/com.rightfontapp.RightFont5")
      ;;
