sketchup2024)
      appTitle="SketchUp"      
      appProcesses+=("SketchUp" "LayOut" "Style Builder" "SketchUp Helper")
      appFiles+=("/Applications/SketchUp 2024/SketchUp.app")
      appFiles+=("/Applications/SketchUp 2024")
      appFiles+=("<<Users>>/Library/Application Scripts/com.sketchup.LayOut.2024.LayOutThumbnailExtension")
      appFiles+=("<<Users>>/Library/Application Scripts/com.sketchup.SketchUp.2024.SketchUpThumbnailExtension")
      appFiles+=("<<Users>>/Library/Application Support/SketchUp 2024")
      appFiles+=("<<Users>>/Library/Caches/com.sketchup.LayOut.2024")
      appFiles+=("<<Users>>/Library/Caches/com.sketchup.SketchUp.2024")
      appFiles+=("<<Users>>/Library/Caches/com.sketchup.StyleBuilder.2024")
      appFiles+=("<<Users>>/Library/Containers/com.sketchup.LayOut.2024.LayOutThumbnailExtension")
      appFiles+=("<<Users>>/Library/Containers/com.sketchup.SketchUp.2024.SketchUpThumbnailExtension")
      appFiles+=("<<Users>>/Library/Preferences/com.sketchup.LayOut.2024.plist")
      appFiles+=("<<Users>>/Library/Preferences/com.sketchup.SketchUp.2024.plist")
      appFiles+=("<<Users>>/Library/Preferences/com.sketchup.StyleBuilder.2024.plist")
      appFiles+=("<<Users>>/Library/Preferences/Trimble.SketchUp-Helper.(Renderer).plist")
      appFiles+=("<<Users>>/LLibrary/Preferences/com.sketchup.StyleBuilder.2024.plist")
      postflightCommand+=("pkill 'SketchUp'")
      ;;
