teamviewer)
      appTitle="TeamViewer"
      appProcesses+=("TeamViewer")
      appFiles+=("/Applications/TeamViewer.app")
      appFiles+=("/Library/Application Support/TeamViewer/")
      appFiles+=("/Library/PrivilegedHelperTools/com.teamviewer.Helper")
      appFiles+=("/Library/Preferences/com.teamviewer.teamviewer.preferences.plist")
      appFiles+=("<<Users>>/Library/Application Support/TeamViewer/")
      appFiles+=("<<Users>>/Library/Preferences/com.teamviewer.TeamViewer.plist")
      appFiles+=("<<Users>>/Library/Preferences/com.teamviewer.teamviewer.preferences.Machine.plist")
      appFiles+=("<<Users>>/Library/Preferences/com.teamviewer.teamviewer.preferences.plist")
      appFiles+=("<<Users>>/Library/Caches/TeamViewer/")
      appFiles+=("<<Users>>/Library/HTTPStorages/com.teamviewer.TeamViewer")
      appFiles+=("<<Users>>/Library/WebKit/com.teamviewer.TeamViewer")
      appLaunchDaemons+=("/Library/LaunchDaemons/com.teamviewer.Helper.plist")
      appLaunchDaemons+=("/Library/LaunchDaemons/com.teamviewer.teamviewer_service.plist")
      appLaunchAgents+=("/Library/LaunchAgents/com.teamviewer.teamviewer_desktop.plist")
      appLaunchAgents+=("/Library/LaunchAgents/com.teamviewer.teamviewer.plist")
      appReceipts+=("com.teamviewer.teamviewer")
      appReceipts+=("com.teamviewer.teamviewerPriviledgedHelper")
      appReceipts+=("com.teamviewer.remoteaudiodriver")     
      appReceipts+=("com.teamviewer.AuthorizationPlugin")
      ;;
