topazphoto|\
topazphotoai)
      appTitle="Topaz Photo AI.app"
      appFiles+=("/Applications/Topaz Photo AI.app")
      appFiles+=("/Applications/Adobe Photoshop 2024/Plug-ins/TopazPhotoAI.plugin")
      appFiles+=("/Applications/Adobe Photoshop 2024/Plug-ins/TopazPhotoAIApply.plugin")
      appFiles+=("/Applications/Adobe Photoshop 2024/Plug-ins/TopazPhotoAIAutomate.plugin")
      appFiles+=("/Applications/Adobe Photoshop 2024/Plug-ins/TopazPhotoAIGather.plugin")
      appFiles+=("/Applications/Adobe Photoshop 2025/Plug-ins/TopazPhotoAI.plugin")
      appFiles+=("/Applications/Adobe Photoshop 2025/Plug-ins/TopazPhotoAIApply.plugin")
      appFiles+=("/Applications/Adobe Photoshop 2025/Plug-ins/TopazPhotoAIAutomate.plugin")
      appFiles+=("/Applications/Adobe Photoshop 2025/Plug-ins/TopazPhotoAIGather.plugin")
      appFiles+=("/Applications/Adobe Photoshop 2026/Plug-ins/TopazPhotoAI.plugin")
      appFiles+=("/Applications/Adobe Photoshop 2026/Plug-ins/TopazPhotoAIApply.plugin")
      appFiles+=("/Applications/Adobe Photoshop 2026/Plug-ins/TopazPhotoAIAutomate.plugin")
      appFiles+=("/Applications/Adobe Photoshop 2026/Plug-ins/TopazPhotoAIGather.plugin")
      appFiles+=("/Library/Application Support/Adobe/Plug-Ins/CC/TopazPhotoAI.plugin")
      appFiles+=("/Library/Application Support/Adobe/Plug-Ins/CC/TopazPhotoAIApply.plugin")
      appFiles+=("/Library/Application Support/Adobe/Plug-Ins/CC/TopazPhotoAIAutomate.plugin")
      appFiles+=("/Library/Application Support/Adobe/Plug-Ins/CC/TopazPhotoAIGather.plugin")
      appFiles+=("<<Users>>/Library/Application Scripts/com.topazlabs.TopazPhotoAIplugin")
      appFiles+=("<<Users>>/Library/Application Support/Topaz Labs LLC/Topaz Photo AI")
      appFiles+=("<<Users>>/Library/Application Support/Adobe/Lightroom/Modules/Topaz Photo AI.lrplugin")
      appFiles+=("<<Users>>/Library/Application Support/Adobe/Lightroom/External Editor Presets/TopazPhotoAI.lrtemplate")
      appFiles+=("<<Users>>/Library/Application Support/Affinity Photo/Plugins/TopazPhotoAI.plugin")
      appReceipts+=("com.topazlabs.TopazPhotoAI")
      ;;
