vmwarefusion)
      appTitle="VMware Fusion"
      appProcesses+=("VMware Fusion")
      appFiles+=("/Applications/VMware Fusion.app")
      appFiles+=("/Library/Application Support/VMware/VMware Fusion")
      appFiles+=("/Library/Application Support/VMware/Usbarb.rules")
      appFiles+=("/Library/Application Support/VMware Fusion")
      appFiles+=("/Library/Preferences/VMware Fusion")
      appFiles+=("/private/etc/paths.d/com.vmware.fusion.public")
      appFiles+=("<<Users>>/Library/Application Support/VMware Fusion")
      appFiles+=("<<Users>>/Library/Caches/com.vmware.fusion")
      appFiles+=("<<Users>>/Library/Preferences/VMware Fusion")
      appFiles+=("<<Users>>/Library/Logs/VMware Fusion")
      appFiles+=("<<Users>>/Library/Preferences/com.vmware.fusion.LSSharedFileList.plist")
      appFiles+=("<<Users>>/Library/Preferences/com.vmware.fusion.LSSharedFileList.plist.lockfile")
      appFiles+=("<<Users>>/Library/Preferences/com.vmware.fusion.plist")
      appFiles+=("<<Users>>/Library/Preferences/com.vmware.fusion.plist.lockfile")
      appFiles+=("<<Users>>/Library/Preferences/com.vmware.fusionDaemon.plist")
      appFiles+=("<<Users>>/Library/Preferences/com.vmware.fusionDaemon.plist.lockfile")
      appFiles+=("<<Users>>/Library/Preferences/com.vmware.fusionStartMenu.plist")
      appFiles+=("<<Users>>/Library/Preferences/com.vmware.fusionStartMenu.plist.lockfile")
      ;;
