wacomdrivers)
      appTitle="Wacom Center"
      appFiles+=("/Applications/Wacom Tablet.localized/Wacom Center.app")
      appFiles+=("/Applications/Wacom Tablet.localized")
      appFiles+=("/Library/Application Support/Tablet/")
      appFiles+=("/Library/Frameworks/WacomMultiTouch.framework")
      appFiles+=("/Library/PreferencePanes/WacomCenter.prefpane")
      appFiles+=("/Library/PreferencePanes/WacomTablet.prefpane")
      appFiles+=("/Library/Preferences/Tablet")
      appFiles+=("/Library/PrivilegedHelperTools/com.wacom.DataStoreMgr.app")
      appFiles+=("/Library/PrivilegedHelperTools/com.wacom.IOManager")
      appFiles+=("/Library/PrivilegedHelperTools/com.wacom.UpdateHelper")
      appFiles+=("<<Users>>/Library/Preferences/com.wacom.ProfessionalTablet.plist")
      appFiles+=("<<Users>>/Library/Preferences/com.wacom.wacomtablet.prefs")
      appFiles+=("<<Users>>/Library/Preferences/com.wacom.wacomtouch.prefs")
      appFiles+=("<<Users>>/Library/Group Containers/EG27766DY7.com.wacom.WacomTabletDriver")
      appFiles+=("<<Users>>/Library/Group Containers/com.wacom.TabletDriver")
      appLaunchAgents+=("/Library/LaunchAgents/com.wacom.DataStoreMgr.plist")
      appLaunchAgents+=("/Library/LaunchAgents/com.wacom.IOManager.plist")
      appLaunchAgents+=("/Library/LaunchAgents/com.wacom.wacomtablet.plist")
      appLaunchDaemons+=("/Library/LaunchDaemons/com.wacom.UpdateHelper.plist")
     ;;
