webex)
		appTitle="Webex"
		appFiles+=("/Applications/Webex.app")
		appFiles+=("<<Users>>/Library/Application Support/WebEx Folder")
		appFiles+=("<<Users>>/Library/Application Support/Webex Meetings")
		appFiles+=("<<Users>>/Library/Application Support/Cisco")
		appFiles+=("<<Users>>/Library/Application Support/Cisco Spark")
		appFiles+=("<<Users>>/Library/Containers/com.cisco.webex.Cisco-WebEx-Start.CWSSafariExtension/Data")
		appFiles+=("<<Users>>/Library/Group Containers/group.com.cisco.webex.meetings")
		appFiles+=("<<Users>>/Library/Saved Application State/Cisco-Systems.Spark.savedState")
		appFiles+=("<<Users>>/Library/Caches/com.cisco.webex.Cisco-WebEx-Start")
		appFiles+=("<<Users>>/Library/Caches/com.cisco.webex.unified.mta")
		appFiles+=("<<Users>>/Caches/com.cisco.webex.webexmta")
		appFiles+=("<<Users>>/Library/Preferences/Cisco-Systems.Spark.plist")
		appFiles+=("<<Users>>/Library/Preferences/com.cisco.meetings.shortcut.plist")
		appFiles+=("<<Users>>/Library/Preferences/com.cisco.webex.Cisco-WebEx-Start.plist")
		appFiles+=("<<Users>>/Library/Preferences/com.cisco.webex.unified.mta.plist")
		appFiles+=("<<Users>>/Library/Preferences/com.cisco.webex.webexmta.plist")
		appFiles+=("<<Users>>/Library/Preferences/com.webex.eventcenter.plist")
		appFiles+=("<<Users>>/Library/Preferences/com.webex.meetingmanager.plist")
		appFiles+=("<<Users>>/Library/WebKit/Cisco-Systems.Spark")
		;;
