whatsapp)
      appTitle="WhatsApp"
      appFiles+=("/Applications/WhatsApp.app")
      appFiles+=("/Users/$loggedInUser/Library/Application Support/WhatsApp")
      appFiles+=("/Users/$loggedInUser/Library/Application Scripts/net.whatsapp.WhatsApp")
      appFiles+=("/Users/$loggedInUser/Library/Caches/WhatsApp")
      appFiles+=("/Users/$loggedInUser/Library/Caches/WhatsApp.ShipIt")
      appFiles+=("/Users/$loggedInUser/Library/Containers/net.whatsapp.WhatsApp")
      appFiles+=("/Users/$loggedInUser/Library/Saved Application State/WhatsApp.savedState")
      appFiles+=("/Users/$loggedInUser/Library/Group Containers/group.net.whatsapp.WhatsApp.private")
      appFiles+=("/Users/$loggedInUser/Library/Group Containers/group.com.facebook.family")
      appFiles+=("/Users/$loggedInUser/Library/Group Containers/group.net.whatsapp.WhatsAppSMB.shared")
      appFiles+=("/Users/$loggedInUser/Library/Group Containers/group.net.whatsapp.WhatsAppSMB.private")
      appFiles+=("/Users/$loggedInUser/Library/Group Containers/group.net.whatsapp.family")
      appFiles+=("/Users/$loggedInUser/Library/Preferences/WhatsApp.plist")
      ;;
